services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\AUTH\Presentation\Http\:
        resource: '../../Presentation/Http'
        tags: [ 'controller.service_arguments' ]'
